[package]
name = "user"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web="4.0.0-beta.10"
actix-protobuf = "0.7.0-beta.2"
env_logger = "0.9.0"
bytes = "1.1.0"
prost= "0.9.0"

[dev-dependencies]
actix-rt = "2.4.0"

[build-dependencies]
prost-build = "0.9.0"